<div class="error-notifice">
    <?php foreach ($this->errors as $error):?>
        <p>*<?php echo $error; ?></p>
    <?php endforeach;?>
</div>
<form class="form-horizontal" action="/user/updatepassword" method="post">
    <input type="hidden" name="password" value="<?php echo $this->password; ?>">
    <div class="form-group">
        <label class="control-label col-sm-4" for="current_password">Mật khẩu được cấp:</label>
        <div class="col-sm-8">
            <input type="text" class="form-control" id="current_password" name="current_password" placeholder="Nhập mật khẩu được cấp" required>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-4" for="new_password">Mật khẩu mới:</label>
        <div class="col-sm-8">
            <input type="password" class="form-control" id="new_password" name="new_password" placeholder="Nhập mật khẩu mới" required>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-4" for="repeat_password">Nhập lại mật khẩu:</label>
        <div class="col-sm-8"> 
            <input type="password" class="form-control" id="repeat_password" name="repeat_password" placeholder="Nhập lại mật khẩu" required>
        </div>
    </div>
    <div class="form-group"> 
        <div class="col-sm-offset-4 col-sm-6">
            <button type="submit" class="btn btn-primary">Lưu thông tin</button>
        </div>
    </div>
</form>