<?php echo $this->doctype('XHTML1_RDFA'); ?>
<html lang="vi">
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">
                        <img src="/images/icon/Vbee_logo.png" height="28" alt="Zend Framework "/>Vbee Application
                    </a>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row wrap-content" data-controller="<?php echo $GLOBALS['controller']?>">
                <div class="col-md-4 left-sidebar">
                    <?php echo $this->partial("layout/left-sitebar.php"); ?>
                </div>
                <div class="col-md-8">
                    <?php echo $this->layout()->content ?>
                </div>
            </div>


            <hr>
            <footer>
                <p>Zend Technologies Ltd. All rights reserved.</p>
                <p>Make by Yin Long.</p>
            </footer>
        </div>
    </body>
</html>