<h1 id="type-action" data-type-name="<?php echo $this->type_name; ?>">
    Danh sách bản update
    <button class="btn btn-success pull-right" id="synchronize">Đồng bộ</button>
</h1>
<a href="#add" class="pull-right" id="add_object">+ Thêm phần update</a>
<div class="row"></div>

<?php echo $this->partial("layout/search.phtml", array('fields' => array('name' => 'Tên'))); ?>
<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Tên</th>
            <th></th>
        </tr>
        <?php echo $this->partial("update/info.phtml", array('order' => 0, 'voice' => array(), 'class' => 'info-pattern')); ?>
    </thead>
    <tbody>
        <?php
        $order = 1;
        foreach ($this->softwares as $software) {
            echo $this->partial("update/info.phtml", array('order' => $order, 'software' => $software));
            $order++;
        }
        ?>
    </tbody>
</table>
<?php
echo $this->partial("layout/process_syn.phtml", array());
echo $this->partial("layout/modal_info.phtml", array('title' => 'Thêm bản update ','action'=>'/update/',
    'fields' => array('name'=>array('type'=>'fileUpload', 'option'=>'Software')),
    'controller_name' => 'update'));
echo $this->partial("layout/modal_remove.phtml", array('title' => 'Xóa bản update '));
echo $this->partial("dictionary/modal_control.phtml", array('title' => 'Đồng bộ bản update',));
