<tr id="dictionary-<?php echo $this->dictionary['id']; ?>" class="<?php echo $this->class; ?>">
    <td class="order"><?php echo $this->order; ?></td>
    <td class="id"><?php echo $this->dictionary['id']; ?></td>
    <td class="word title"><?php echo $this->dictionary['word']; ?></td>
    <td class="spelling"><?php echo $this->dictionary['spelling']; ?></td>
    <td><a href="#edit" class="edit_object">Edit</a> <a href="#remove" class="remove_object">Remove</a></td>
</tr>