<div id="modal_control" class="modal fade" role="dialog" data-backdrop="static" data-id="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo $this->title; ?></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <p>Bạn muốn đồng bộ từ điển?</p>
                    <div class="checkbox">
                        <label><input type="checkbox" name="restart"> Khởi động lại server</label>
                    </div>
                    <div class="col-sm-10"><p class="error-notifice"></p></div>
                </form>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-info action">Ok</button>
            </div>
        </div>

    </div>
</div>