<div class="form-group">
    <label for="input<?php echo $this->name; ?>" class="col-sm-2 control-label"><?php echo $this->option; ?></label>
    <div class="col-sm-10">
        <input type="text" class="form-control non-required" id="input<?php echo $this->name; ?>" name="<?php echo $this->name; ?>" value="<?php echo $this->default; ?>" data-default="<?php echo $this->default; ?>" disabled>
    </div>
</div>